/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PulgasLocas.GUI;

import PulgasLocas.Juego.Simulador;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;

/**
 *
 * @author santi
 */
public class MainWindow extends javax.swing.JFrame {

    private Simulador garden;
    
    /**
     * Creates new form MainWindow
     */
    private double maxScore;
    public MainWindow() {
        initComponents();
        maxScore = 0;
        DialogNombre dialog = new DialogNombre(this,true,this.getMaxScore());
        dialog.setVisible(true);
        
    }
    
    public double getMaxScore(){
        return maxScore;
    }
    public void setGarden(Simulador garden){
        this.garden = garden;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        garden.draw(g);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Score: ");

        lScore.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lScore)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lScore))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyChar() == 'q'){
            System.exit(0);
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_S | evt.getKeyCode() == KeyEvent.VK_H | evt.getKeyCode() == KeyEvent.VK_P){
            garden.keyPressed(evt.getKeyCode());
            repaint();
        }


    }//GEN-LAST:event_formKeyPressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        garden.mouseClicked(evt.getX(), evt.getY(),evt.getButton());
        repaint();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MainWindow window = new MainWindow();
        window.setSize(800, 600);
        window.setTitle("Simulador de Pulgas locas");
        
        Simulador garden = new Simulador(0, 0, window.getWidth(), window.getHeight());
        window.setGarden(garden);
        window.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lScore;
    // End of variables declaration//GEN-END:variables
}
