/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PulgasLocas.GUI;

import PulgasLocas.Juego.Simulador;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;

/**
 *
 * @author santi
 */
public class MainWindow extends javax.swing.JFrame {

    private Simulador garden;
    
    /**
     * Creates new form MainWindow
     */
    private double maxScore;
    private int width;
    private int height;
    private String nombre;
    private DialogNombre dialog;
    public MainWindow(int width, int height) {
        initComponents();
        maxScore = 0;
        this.width = width;
        this.height = height;
        this.setSize(width, height);
        dialog = new DialogNombre(this,true,this.getMaxScore());
        dialog.setVisible(true);
        nombre = dialog.getNombre();
        lNombre.setText(nombre);
        Simulador garden = new Simulador(width, height);
        this.setGarden(garden);
        this.setTitle("Simulador de Pulgas locas");
        this.setVisible(true);
    }
    
    public double getMaxScore(){
        return maxScore;
    }
    public void setGarden(Simulador garden){
        this.garden = garden;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        garden.draw(g);
        lNombre.setText(nombre);
        lNombre.setVisible(true);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNombre = new javax.swing.JLabel();
        lScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lNombre.setText("Score: ");

        lScore.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(lNombre)
                .addGap(18, 18, 18)
                .addComponent(lScore)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(lScore))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyChar() == 'q'){
            acabar();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_S | evt.getKeyCode() == KeyEvent.VK_H | evt.getKeyCode() == KeyEvent.VK_P){
            garden.keyPressed(evt.getKeyCode());
            repaint();
            lNombre.setText(nombre);
            lNombre.setVisible(true);
        }
        
        if(garden.juegoAcabado()){
            acabar();
        }


    }//GEN-LAST:event_formKeyPressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        garden.mouseClicked(evt.getX(), evt.getY(),evt.getButton());
        repaint();
        lNombre.setText(nombre);
        lNombre.setVisible(true);
        if(garden.juegoAcabado()){
            acabar();
        }
    }//GEN-LAST:event_formMousePressed

    public void acabar(){
        if(maxScore < garden.getScore()){
            maxScore = garden.getScore();
        }
        dialog.setNombre(nombre);
        dialog.setMaxScore(getMaxScore());
        Simulador garden = new Simulador(width, height);
        this.setGarden(garden);
        dialog.setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MainWindow window = new MainWindow(800, 600);
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lScore;
    // End of variables declaration//GEN-END:variables
}
